apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-29T17:30:43Z"
  generation: 1
  labels:
    app: echodep
  name: echodep
  namespace: default
  resourceVersion: "1401"
  selfLink: /apis/apps/v1/namespaces/default/deployments/echodep
  uid: 13cd88c6-42bd-11ea-9efa-42010a9a011a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echodep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echodep
    spec:
      containers:
      - image: gcr.io/website-project-263812/echoservice:v1
        imagePullPolicy: IfNotPresent
        name: echoservice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-29T17:31:17Z"
    lastUpdateTime: "2020-01-29T17:31:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-29T17:30:43Z"
    lastUpdateTime: "2020-01-29T17:31:17Z"
    message: ReplicaSet "echodep-848c54db9d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
